# ====================
# WIN THE LOTTERY
# ====================

'''
What you needa doz
1. Random number generated by Python lel
2. Get input from user
3. Loop If else statements
4. Print result
'''
# task 1
import random
rand = random.randint(1,100) # a random int number will be generated between 1 ~ 99

# task 3
for i in range(5): # range(5) starts from 0... So yeah.
	# task 2
	print("Please enter a number between 1 to 99 as your guess. You only have 5 chances. May the odds ever be in your favour. >=D")
	user_try = int(input())

	# cont. task 3
	if(user_try < rand):
		print("Nope. A little higher.")
	elif(user_try > rand):
		print("Overshot. Boo.")
	else:
		break # user is correctzo

if (user_try == rand):
	print("OMG. ARE YOU A SEER?")
else:
	print("HAHAHAHHA. LOSERRRRRRRR.")	